const LinkedInSelector = {
    HOME: "https://www.linkedin.com/",
    CONNECTION_PAGE: "https://www.linkedin.com/mynetwork/invite-connect/connections/",
    LOGIN_PAGE: "https://www.linkedin.com/login?trk=homepage-basic_ispen-login-button",
    LoginCheck: ".global-nav__me-photo",
    UserName: "[name=session_key]",
    Password: "[name=session_password]",
    LoginBtn: ".login__form_action_container > button",
    LEAD_NAME: ".pv-text-details__left-panel div h1",
    ProfilePageBtn: ".pv-top-card-v2-ctas > .pvs-profile-actions",
    ProfileMoreBtn: ".pv-top-card-v2-ctas > .pvs-profile-actions",
    connectBtn_1: ".pv-top-card-v2-ctas > .pvs-profile-actions > button",
    FollowBtn: '[data-control-name="topcard_primary_follow"]',
    conneconnectBtn_message_tab: "/html/body/div[3]/div/div/div[3]/button[1]",
    connectReqMgsTextArea: "#custom-message",
    connectBtn_2: "/html/body/div[3]/div/div/div[3]/button[2]/span",
    Profile_msg_btn: ".pv-top-card-v2-ctas > .pvs-profile-actions > .entry-point",
    MessageTabClass: ".msg-convo-wrapper",
    MessageTextArea: ".msg-form__contenteditable p",
    ConnectionListPage: ".entity-result__item",
    ConnectionListPageAction: ".entity-result__actions",
    ConnectionName: ".entity-result__title-text > a > span > span",
    ConnectionLink: ".entity-result__title-text > .app-aware-link",
    No_Result_Found: ".reusable-search-filters__no-results",
    ProfilePage_action_btn: ".pv-top-card-v2-ctas > .pvs-profile-actions button",
    ProfilePage_more_btn: ".pv-top-card-v2-ctas > .pvs-profile-actions button > span",
    ProfilePage_More_dropdown: '.pvs-overflow-actions-dropdown__content',
    ProfilePage_More_dropdown_action_text: '.pv-top-card-v2-ctas > .pvs-profile-actions > .artdeco-dropdown > .pvs-overflow-actions-dropdown__content ul > li > div > span',
    ProfilePage_more_dropdown_connect_btn: '.send-invite > .artdeco-modal__actionbar > button',
    OTP_INPUT: "#input__email_verification_pin",
    OTP_SUBMIT: "#email-pin-submit-button",
};
module.exports = LinkedInSelector;