server:
  port: 5025
spring:
  application:
    name: TEMPLATE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/pulpy-template
    username: sharuk
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        jdbc:
          time_zone: UTC

